### ISSUE TITLE
Name conflict with pyhumps: what's the difference? :thinking: 

### ISSUE THREAD

**Issue by eliasdorneles** [erikhuizinga/humps#1]
Hello,

It seems this package `humps` has a name conflict with https://github.com/nficano/humps which uses the PyPI name `pyhumps`

I'm wondering, what's the difference between the two?
Does this package does something that pyhumps doesn't do?

**Comment by erikhuizinga** [comment]
Hi, thanks for your contribution and interest in this project.

I'm not actively maintaining this repository anymore. I don't know nficano/humps, so I can't tell you about the differences. If you want, feel free to contribute any changes you think this project might need. For example, this project might need a different package name, or features that the other project doesn't have to make it useful compared to the other package.

Let me know if you need anything else. Otherwise, I'm closing this issue for now, as there currently is no action to take.
